var data = {
    'resultxml': {
        'msg': 'true',
        'success': 'true',
        'circuit': {
            'int_id': '95105040505de0bf7900f4e82bd710c96cb625171',
            'zh_label': '中卫-北京100GE5000NP/KA/λ',
            'a_transne_id': '6410102012201HWCSANEL6e0ce43bc458f4d6',
            'a_transne_id_value': 'ZW-17338-NX中卫云基地-N-HW-EXC-1',
            'z_transne_id': '1110102012201HWCSANELf83cc4455eb6bd24',
            'z_transne_id_value': 'ZW-17367-BJ北京大白楼-N-HW-EXC-1',
            'a_transequiproom_id': '642010103184794956',
            'a_transequiproom_value': '宁夏中卫市沙坡头区数据中心一号机楼1204机房',
            'z_transequiproom_id': '1120101031506770869',
            'z_transequiproom_value': '大兴区大白楼二期通信枢纽楼位置点2层传输骨干1机房',
            'a_port_id': 'n1-1-1',
            'z_port_id': 'n1-4-out',
            'path': [
                {
                    'z_ne_id': '1110102012201HWCSANELf83cc4455eb6bd24',
                    'z_ne_name': 'ZW-17367-BJ北京大白楼-N-HW-EXC-1',
                    'a_ne_id': '6410102012201HWCSANEL6e0ce43bc458f4d6',
                    'a_ne_name': 'ZW-17338-NX中卫云基地-N-HW-EXC-1',
                    'route': [
                        [{
                            'a_ne_id': 'n1-1',
                            'a_ne_name': 'ZW-17338-NX中卫云基地-N-HW-EXC-1',
                            'a_port_id': 'n1-1-1',
                            'a_port_name': 'ZW-17338-NX中卫云基地-N-HW-EXC-1-in',
                            'z_ne_id': 'n1-1',
                            'z_ne_name': 'ZW-17338-NX中卫云基地-N-HW-EXC-1',
                            'z_port_id': 'n1-1-2',
                            'z_port_name': 'ZW-17338-NX中卫云基地-N-HW-EXC-1-out'
                        }, {
                            'a_ne_id': 'n1-1',
                            'a_ne_name': 'ZW-17338-NX中卫云基地-N-HW-EXC-1',
                            'a_port_id': 'n1-1-2',
                            'a_port_name': 'ZW-17338-NX中卫云基地-N-HW-EXC-1-out',
                            'z_ne_id': 'n1-2',
                            'z_ne_name': 'ZW-15482-NX中卫云基地-N-HW-OTM-1',
                            'z_port_id': 'n1-2-1',
                            'z_port_name': 'ZW-15482-NX中卫云基地-N-HW-OTM-1-in'
                        }, {
                            'a_ne_id': 'n1-2',
                            'a_ne_name': 'ZW-15482-NX中卫云基地-N-HW-OTM-1',
                            'a_port_id': 'n1-2-1',
                            'a_port_name': 'ZW-15482-NX中卫云基地-N-HW-OTM-1-in',
                            'z_ne_id': 'n1-2',
                            'z_ne_name': 'ZW-15482-NX中卫云基地-N-HW-OTM-1',
                            'z_port_id': 'n1-2-2',
                            'z_port_name': 'ZW-15482-NX中卫云基地-N-HW-OTM-1-out'
                        }, {
                            'a_ne_id': 'n1-2',
                            'a_ne_name': 'ZW-15482-NX中卫云基地-N-HW-OTM-1',
                            'a_port_id': 'n1-2-2',
                            'a_port_name': 'ZW-15482-NX中卫云基地-N-HW-OTM-1-out',
                            'z_ne_id': 'n1-3',
                            'z_ne_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335',
                            'z_port_id': 'n1-3-1',
                            'z_port_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335-in'
                        }, {
                            'a_ne_id': 'n1-3',
                            'a_ne_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335',
                            'a_port_id': 'n1-3-1',
                            'a_port_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335-in',
                            'z_ne_id': 'n1-3',
                            'z_ne_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335',
                            'z_port_id': 'n1-3-2',
                            'z_port_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335-out'
                        }, {
                            'a_ne_id': 'n1-3',
                            'a_ne_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335',
                            'a_port_id': 'n1-3-2',
                            'a_port_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335-out',
                            'z_ne_id': 'n1-4',
                            'z_ne_name': 'ZW-16149-NX中宁石空-N-HW-OA-M6335',
                            'z_port_id': 'n1-4-in',
                            'z_port_name': 'ZW-16149-NX中宁石空-N-HW-OA-M6335-in',
                        }, {
                            'a_ne_id': 'n1-4',
                            'a_ne_name': 'ZW-16149-NX中宁石空-N-HW-OA-M6335',
                            'a_port_id': 'n1-4-in',
                            'a_port_name': 'ZW-16149-NX中宁石空-N-HW-OA-M6335-in',
                            'z_ne_id': 'n1-4',
                            'z_ne_name': 'ZW-16149-NX中宁石空-N-HW-OA-M6335',
                            'z_port_id': 'n1-4-out',
                            'z_port_name': 'ZW-16149-NX中宁石空-N-HW-OA-M6335-out'
                        }],
                        [{
                            'a_ne_id': 'n1-1',
                            'a_ne_name': 'ZW-17338-NX中卫云基地-N-HW-EXC-1',
                            'a_port_id': 'n1-1-1',
                            'a_port_name': 'ZW-17338-NX中卫云基地-N-HW-EXC-1-in',
                            'z_ne_id': 'n1-1',
                            'z_ne_name': 'ZW-17338-NX中卫云基地-N-HW-EXC-1',
                            'z_port_id': 'n2-1-2',
                            'z_port_name': 'ZW-17338-NX中卫云基地-N-HW-EXC-1-out'
                        }, {
                            'a_ne_id': 'n1-1',
                            'a_ne_name': 'ZW-17338-NX中卫云基地-N-HW-EXC-1',
                            'a_port_id': 'n2-1-2',
                            'a_port_name': 'ZW-17338-NX中卫云基地-N-HW-EXC-1-out',
                            'z_ne_id': 'n2-2',
                            'z_ne_name': 'ZW-15482-NX中卫云基地-N-HW-OTM-1',
                            'z_port_id': 'n2-2-1',
                            'z_port_name': 'ZW-15482-NX中卫云基地-N-HW-OTM-1-in'
                        }, {
                            'a_ne_id': 'n2-2',
                            'a_ne_name': 'ZW-15482-NX中卫云基地-N-HW-OTM-1',
                            'a_port_id': 'n2-2-1',
                            'a_port_name': 'ZW-15482-NX中卫云基地-N-HW-OTM-1-in',
                            'z_ne_id': 'n2-2',
                            'z_ne_name': 'ZW-15482-NX中卫云基地-N-HW-OTM-1',
                            'z_port_id': 'n2-2-2',
                            'z_port_name': 'ZW-15482-NX中卫云基地-N-HW-OTM-1-out'
                        }, {
                            'a_ne_id': 'n2-2',
                            'a_ne_name': 'ZW-15482-NX中卫云基地-N-HW-OTM-1',
                            'a_port_id': 'n2-2-2',
                            'a_port_name': 'ZW-15482-NX中卫云基地-N-HW-OTM-1-out',
                            'z_ne_id': 'n2-3',
                            'z_ne_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335',
                            'z_port_id': 'n2-3-1',
                            'z_port_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335-in'
                        }, {
                            'a_ne_id': 'n2-3',
                            'a_ne_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335',
                            'a_port_id': 'n2-3-1',
                            'a_port_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335-in',
                            'z_ne_id': 'n2-3',
                            'z_ne_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335',
                            'z_port_id': 'n2-3-2',
                            'z_port_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335-out'
                        }, {
                            'a_ne_id': 'n2-3',
                            'a_ne_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335',
                            'a_port_id': 'n2-3-2',
                            'a_port_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335-out',
                            'z_ne_id': 'n2-4',
                            'z_ne_name': 'ZW-16149-NX中宁石空-N-HW-OA-M6335',
                            'z_port_id': 'n2-4-1',
                            'z_port_name': 'ZW-16149-NX中宁石空-N-HW-OA-M6335-in',
                        }, {
                            'a_ne_id': 'n2-4',
                            'a_ne_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335',
                            'a_port_id': 'n2-4-1',
                            'a_port_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335-in',
                            'z_ne_id': 'n2-4',
                            'z_ne_name': 'ZW-16149-NX中宁石空-N-HW-OA-M6335',
                            'z_port_id': 'n2-4-2',
                            'z_port_name': 'ZW-16149-NX中宁石空-N-HW-OA-M6335-out',
                        }, {
                            'a_ne_id': 'n2-4',
                            'a_ne_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335',
                            'a_port_id': 'n2-4-2',
                            'a_port_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335-out',
                            'z_ne_id': 'n2-5',
                            'z_ne_name': 'ZW-16149-NX中宁石空-N-HW-OA-M6335',
                            'z_port_id': 'n2-5-1',
                            'z_port_name': 'ZW-16149-NX中宁石空-N-HW-OA-M6335-in',
                        }, {
                            'a_ne_id': 'n2-5',
                            'a_ne_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335',
                            'a_port_id': 'n2-5-1',
                            'a_port_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335-out',
                            'z_ne_id': 'n2-5',
                            'z_ne_name': 'ZW-16149-NX中宁石空-N-HW-OA-M6335',
                            'z_port_id': 'n2-5-2',
                            'z_port_name': 'ZW-16149-NX中宁石空-N-HW-OA-M6335-in',
                        }, {
                            'a_ne_id': 'n2-5',
                            'a_ne_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335',
                            'a_port_id': 'n2-5-2',
                            'a_port_name': 'ZW-16148-NX中卫二中心-N-HW-OA-M6335-out',
                            'z_ne_id': 'n1-4',
                            'z_ne_name': 'ZW-16149-NX中宁石空-N-HW-OA-M6335',
                            'z_port_id': 'n2-4-in',
                            'z_port_name': 'ZW-16149-NX中宁石空-N-HW-OA-M6335-in',
                        }, {
                            'a_ne_id': 'n1-4',
                            'a_ne_name': 'ZW-16149-NX中宁石空-N-HW-OA-M6335',
                            'a_port_id': 'n2-4-in',
                            'a_port_name': 'ZW-16149-NX中宁石空-N-HW-OA-M6335-in',
                            'z_ne_id': 'n1-4',
                            'z_ne_name': 'ZW-16149-NX中宁石空-N-HW-OA-M6335',
                            'z_port_id': 'n1-4-out',
                            'z_port_name': 'ZW-16149-NX中宁石空-N-HW-OA-M6335-out'
                        }]
                    ]
                }
            ]
        }
    }

}

