stages:
    - info
    - webinstall
    - package
    - copy_tar_to_repo
    - deploy
    - send_email

variables:
    REPO_DIR: '/opt/tomcat-repo/webapps/sotn-webapp/package'

info:
    stage: info
    only:
        # - master
        - develop
        # - /^release_.*$/
        # - /^branch_.*$/
    script:
        - whoami
        - pwd
        - export

webinstall:
    stage: webinstall
    only:
        # - master
        - develop
        # - /^release_.*$/
        # - /^branch_.*$/
    cache:
        key: release_tar
        paths:
            - node_modules/
            - build/
    script:
        - yarn
        - npm run build

package:
    stage: package
    only:
        # - master
        - develop
        # - /^release_.*$/
        # - /^branch_.*$/
    cache:
        key: release_tar
        paths:
            - build.tar.gz
    script:
        - tar cvf build.tar build
        - gzip build.tar

copy_tar_to_repo:
    stage: copy_tar_to_repo
    only:
        # - master
        - develop
        # - /^release_.*$/
        # - /^branch_.*$/
    cache:
        key: release_tar
        paths:
            - build.tar.gz
    script:
        - cp build.tar.gz $REPO_DIR/

deploy:
    stage: deploy
    only:
        # - master
        - develop
        # - /^release_.*$/
        # - /^branch_.*$/
    cache:
        key: release_tar
        paths:
            - build.tar.gz
    script:
        - bash tools/deploy-sotn-webapp.sh

# send_email:
#     stage: send_email
#     only:
#         - master
#         - develop
#         - /^release_.*$/
#         - /^branch_.*$/
#     script:
#         - bash tools/sendemail
